sudo: false
language: node_js
node_js:
  - '6.1'
cache:
  directories:
  - node_modules
before_script:
  - npm install -g bower
  - bower install
# Borrowed from https://github.com/dojo/core/blob/master/.travis.yml
install:
- travis_retry npm install grunt-cli $(node -e "var deps = require('./package.json').peerDependencies;
  for(var name in deps) process.stdout.write(name + '@' + deps[name] + ' ');")
- travis_retry npm install

script:
- grunt
- node_modules/.bin/intern-runner config=tests/intern
