sudo: required  
dist: trusty  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - NPM_VERSION=3
language: node_js
node_js:
  - '6.1'
cache:
  directories:
  - node_modules
# Borrowed from https://github.com/dojo/core/blob/master/.travis.yml
install:
- travis_retry npm install grunt-cli $(node -e "var deps = require('./package.json').peerDependencies;
  for(var name in deps) process.stdout.write(name + '@' + deps[name] + ' ');")
- travis_retry npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - npm install -g bower
  - bower install
script:
- grunt
- node_modules/.bin/intern-runner config=tests/intern
